export const CHANNEL_LIST_REQUEST = 'CHANNEL_LIST_REQUEST';
export const CHANNEL_LIST_SUCCESS = 'CHANNEL_LIST_SUCCESS';
export const CHANNEL_LIST_FAIL = 'CHANNEL_LIST_FAIL';

export const CHANNEL_POSTS_REQUEST = 'CHANNEL_POSTS_REQUEST';
export const CHANNEL_POSTS_SUCCESS = 'CHANNEL_POSTS_SUCCESS';
export const CHANNEL_POSTS_RESET = 'CHANNEL_POSTS_RESET';
export const CHANNEL_POSTS_FAIL = 'CHANNEL_POSTS_FAIL';

export const CHANNEL_ADD_REQUEST = 'CHANNEL_ADD_REQUEST';
export const CHANNEL_ADD_SUCCESS = 'CHANNEL_ADD_SUCCESS';
export const CHANNEL_ADD_FAIL = 'CHANNEL_ADD_FAIL';
export const CHANNEL_ADD_RESET = 'CHANNEL_ADD_RESET';

export const CHANNEL_PIN_REQUEST = 'CHANNEL_PIN_REQUEST';
export const CHANNEL_PIN_SUCCESS = 'CHANNEL_PIN_SUCCESS';
export const CHANNEL_PIN_FAIL = 'CHANNEL_PIN_FAIL';

export const CHANNEL_DELETE_REQUEST = 'CHANNEL_DELETE_REQUEST';
export const CHANNEL_DELETE_SUCCESS = 'CHANNEL_DELETE_SUCCESS';
export const CHANNEL_DELETE_FAIL = 'CHANNEL_DELETE_FAIL';
export const CHANNEL_DELETE_RESET = 'CHANNEL_DELETE_RESET';

export const CHANNEL_DETAIL_REQUEST = 'CHANNEL_DETAIL_REQUEST';
export const CHANNEL_DETAIL_SUCCESS = 'CHANNEL_DETAIL_SUCCESS';
export const CHANNEL_DETAIL_FAIL = 'CHANNEL_DETAIL_FAIL';
