export const CHANNEL_LIST_REQUEST = "CHANNEL_LIST_REQUEST";
export const CHANNEL_LIST_SUCCESS = "CHANNEL_LIST_SUCCESS";
export const CHANNEL_LIST_FAIL = "CHANNEL_LIST_FAIL";

export const CHANNEL_POSTS_REQUEST = "CHANNEL_POSTS_REQUEST";
export const CHANNEL_POSTS_SUCCESS = "CHANNEL_POSTS_SUCCESS";
export const CHANNEL_POSTS_FAIL = "CHANNEL_POSTS_FAIL";
