export const LIST_MESSAGE_REQUEST = 'LIST_MESSAGE_REQUEST';
export const LIST_MESSAGE_SUCCESS = 'LIST_MESSAGE_SUCCESS';
export const LIST_MESSAGE_FAIL = 'LIST_MESSAGE_FAIL';

export const DETAIL_MESSAGE_REQUEST = 'DETAIL_MESSAGE_REQUEST';
export const DETAIL_MESSAGE_SUCCESS = 'DETAIL_MESSAGE_SUCCESS';
export const DETAIL_MESSAGE_FAIL = 'DETAIL_MESSAGE_FAIL';

export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_FAIL = 'SEARCH_USER_FAIL';

export const CONNECT_SOCKET_REQUEST = 'CONNECT_SOCKET_REQUEST';
export const CONNECT_SOCKET_SUCCESS = 'CONNECT_SOCKET_SUCCESS';
export const CONNECT_SOCKET_FAIL = 'CONNECT_SOCKET_FAIL';
export const DISCONNECT_SOCKET = 'DISCONNECT_SOCKET';
