export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_FAIL = 'POST_LIST_FAIL';
export const POST_LIST_RESET = 'POST_LIST_RESET';

export const POST_SUBMIT_REQUEST = 'POST_SUBMIT_REQUEST';
export const POST_SUBMIT_SUCCESS = 'POST_SUBMIT_SUCCESS';
export const POST_SUBMIT_FAIL = 'POST_SUBMIT_FAIL';
export const POST_SUBMIT_RESET = 'POST_SUBMIT_RESET';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS';
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL';

export const MENU_BAR_REQUEST = 'MENU_BAR_REQUEST';
export const MENU_BAR_SUCCESS = 'MENU_BAR_SUCCESS';
export const MENU_BAR_FAIL = 'MENU_BAR_FAIL';

export const POST_LIST_PROFILE_REQUEST = 'POST_LIST_PROFILE_REQUEST';
export const POST_LIST_PROFILE_SUCCESS = 'POST_LIST_PROFILE_SUCCESS';
export const POST_LIST_PROFILE_FAIL = 'POST_LIST_PROFILE_FAIL';
export const POST_LIST_PROFILE_RESET = 'POST_LIST_PROFILE_RESET';

export const POST_BOOKMARK_REQUEST = 'POST_BOOKMARK_REQUEST';
export const POST_BOOKMARK_SUCCESS = 'POST_BOOKMARK_SUCCESS';
export const POST_BOOKMARK_FAIL = 'POST_BOOKMARK_FAIL';

export const POST_HEART_REQUEST = 'POST_HEART_REQUEST';
export const POST_HEART_SUCCESS = 'POST_HEART_SUCCESS';
export const POST_HEART_FAIL = 'POST_HEART_FAIL';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_RESET = 'POST_DELETE_RESET';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';

export const POST_REPORT_REQUEST = 'POST_REPORT_REQUEST';
export const POST_REPORT_SUCCESS = 'POST_REPORT_SUCCESS';
export const POST_REPORT_FAIL = 'POST_REPORT_FAIL';

export const POST_UN_REPORT_REQUEST = 'POST_UN_REPORT_REQUEST';
export const POST_UN_REPORT_SUCCESS = 'POST_UN_REPORT_SUCCESS';
export const POST_UN_REPORT_FAIL = 'POST_UN_REPORT_FAIL';

export const POST_UPLOAD_IMAGE_REQUEST = 'POST_UPLOAD_IMAGE_REQUEST';
export const POST_UPLOAD_IMAGE_SUCCESS = 'POST_UPLOAD_IMAGE_SUCCESS';
export const POST_UPLOAD_IMAGE_FAIL = 'POST_UPLOAD_IMAGE_FAIL';
export const POST_UPLOAD_IMAGE_RESET = 'POST_UPLOAD_IMAGE_RESET';

export const POST_DELETE_PHOTO_REQUEST = 'POST_DELETE_PHOTO_REQUEST';
export const POST_DELETE_PHOTO_SUCCESS = 'POST_DELETE_PHOTO_SUCCESS';
export const POST_DELETE_PHOTO_FAIL = 'POST_DELETE_PHOTO_FAIL';

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL';

export const POST_REPLY_ALL_REQUEST = 'POST_REPLY_ALL_REQUEST';
export const POST_REPLY_ALL_SUCCESS = 'POST_REPLY_ALL_SUCCESS';
export const POST_REPLY_ALL_FAIL = 'POST_REPLY_ALL_FAIL';
export const POST_REPLY_ALL_RESET = 'POST_REPLY_ALL_RESET';

export const SET_POST_ACTIVE = 'SET_POST_ACTIVE';
