export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR_RESET = 'USER_LOGIN_ERROR_RESET';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const CHECK_ACCOUNT_REQUEST = 'CHECK_ACCOUNT_REQUEST';
export const CHECK_ACCOUNT_SUCCESS = 'CHECK_ACCOUNT_SUCCESS';
export const CHECK_ACCOUNT_FAIL = 'CHECK_ACCOUNT_FAIL';
export const CHECK_ACCOUNT_RESET = 'CHECK_ACCOUNT_RESET';

export const CHECK_NUMBER_PHONE_REQUEST = 'CHECK_NUMBER_PHONE_REQUEST';
export const CHECK_NUMBER_PHONE_SUCCESS = 'CHECK_NUMBER_PHONE_SUCCESS';
export const CHECK_NUMBER_PHONE_FAIL = 'CHECK_NUMBER_PHONE_FAIL';
export const CHECK_NUMBER_PHONE_RESET = 'CHECK_NUMBER_PHONE_RESET';

export const CHECK_USER_EMAIL_REQUEST = 'CHECK_USER_EMAIL_REQUEST';
export const CHECK_USER_EMAIL_SUCCESS = 'CHECK_USER_EMAIL_SUCCESS';
export const CHECK_USER_EMAIL_FAIL = 'CHECK_USER_EMAIL_FAIL';
export const CHECK_USER_EMAIL_RESET = 'CHECK_USER_EMAIL_RESET';
export const SAVE_USER_EMAIL_TEMPORARY = 'SAVE_USER_EMAIL_TEMPORARY';
export const SAVE_USER_NUMBER_PHONE_TEMPORARY =
    'SAVE_USER_NUMBER_PHONE_TEMPORARY';

export const USER_CODE_REQUEST = 'USER_CODE_REQUEST';
export const USER_CODE_SUCCESS = 'USER_CODE_SUCCESS';
export const USER_CODE_FAIL = 'USER_CODE_FAIL';
export const USER_CODE_RESET = 'USER_CODE_RESET';

export const USER_UPDATE_AVATAR_REQUEST = 'USER_UPDATE_AVATAR_REQUEST';
export const USER_UPDATE_AVATAR_SUCCESS = 'USER_UPDATE_AVATAR_SUCCESS';
export const USER_UPDATE_AVATAR_FAIL = 'USER_UPDATE_AVATAR_FAIL';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET';

export const USER_THEME_SUCCESS = 'USER_THEME_SUCCESS';
export const USER_THEME_RESET = 'USER_THEME_RESET';

export const USER_PROFILE_STRANGER_REQUEST = 'USER_PROFILE_STRANGER_REQUEST';
export const USER_PROFILE_STRANGER_SUCCESS = 'USER_PROFILE_STRANGER_SUCCESS';
export const USER_PROFILE_STRANGER_FAIL = 'USER_PROFILE_STRANGER_FAIL';
export const USER_PROFILE_STRANGER_RESET = 'USER_PROFILE_STRANGER_RESET';

export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST';
export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS';
export const USER_FOLLOW_RESET = 'USER_FOLLOW_RESET';
export const USER_FOLLOW_FAIL = 'USER_FOLLOW_FAIL';

export const USER_LIST_FOLLOW_REQUEST = 'USER_LIST_FOLLOW_REQUEST';
export const USER_LIST_FOLLOW_SUCCESS = 'USER_LIST_FOLLOW_SUCCESS';
export const USER_LIST_FOLLOW_FAIL = 'USER_LIST_FOLLOW_FAIL';

export const USER_BLOCK_REQUEST = 'USER_BLOCK_REQUEST';
export const USER_BLOCK_SUCCESS = 'USER_BLOCK_SUCCESS';
export const USER_BLOCK_FAIL = 'USER_BLOCK_FAIL';

export const USER_MUTE_REQUEST = 'USER_MUTE_REQUEST';
export const USER_MUTE_SUCCESS = 'USER_MUTE_SUCCESS';
export const USER_MUTE_FAIL = 'USER_MUTE_FAIL';

export const USER_LIST_BLOCK_REQUEST = 'USER_LIST_BLOCK_REQUEST';
export const USER_LIST_BLOCK_SUCCESS = 'USER_LIST_BLOCK_SUCCESS';
export const USER_LIST_BLOCK_FAIL = 'USER_LIST_BLOCK_FAIL';

export const USER_LIST_MUTE_REQUEST = 'USER_LIST_MUTE_REQUEST';
export const USER_LIST_MUTE_SUCCESS = 'USER_LIST_MUTE_SUCCESS';
export const USER_LIST_MUTE_FAIL = 'USER_LIST_MUTE_FAIL';

export const POST_LIST_PROFILE_STRANGER_REQUEST =
    'POST_LIST_PROFILE_STRANGER_REQUEST';
export const POST_LIST_PROFILE_STRANGER_SUCCESS =
    'POST_LIST_PROFILE_STRANGER_SUCCESS';
export const POST_LIST_PROFILE_STRANGER_FAIL =
    'POST_LIST_PROFILE_STRANGER_FAIL';

export const USER_UPLOAD_AVATAR_REQUEST = 'USER_UPLOAD_AVATAR_REQUEST';
export const USER_UPLOAD_AVATAR_SUCCESS = 'USER_UPLOAD_AVATAR_SUCCESS';
export const USER_UPLOAD_AVATAR_FAIL = 'USER_UPLOAD_AVATAR_FAIL';

export const USER_GET_FOLLOWER_REQUEST = 'USER_GET_FOLLOWER_REQUEST';
export const USER_GET_FOLLOWER_SUCCESS = 'USER_GET_FOLLOWER_SUCCESS';
export const USER_GET_FOLLOWER_FAIL = 'USER_GET_FOLLOWER_FAIL';

export const USER_GET_FOLLOWING_REQUEST = 'USER_GET_FOLLOWING_REQUEST';
export const USER_GET_FOLLOWING_SUCCESS = 'USER_GET_FOLLOWING_SUCCESS';
export const USER_GET_FOLLOWING_FAIL = 'USER_GET_FOLLOWING_FAIL';

export const USER_GET_FOLLOWER_STRANGER_REQUEST =
    'USER_GET_FOLLOWER_STRANGER_REQUEST';
export const USER_GET_FOLLOWER_STRANGER_SUCCESS =
    'USER_GET_FOLLOWER_STRANGER_SUCCESS';
export const USER_GET_FOLLOWER_STRANGER_FAIL =
    'USER_GET_FOLLOWER_STRANGER_FAIL';

export const USER_GET_FOLLOWING_STRANGER_REQUEST =
    'USER_GET_FOLLOWING_STRANGER_REQUEST';
export const USER_GET_FOLLOWING_STRANGER_SUCCESS =
    'USER_GET_FOLLOWING_STRANGER_SUCCESS';
export const USER_GET_FOLLOWING_STRANGER_FAIL =
    'USER_GET_FOLLOWING_STRANGER_FAIL';

export const USER_SHARE_POST_REQUEST = 'USER_SHARE_POST_REQUEST';
export const USER_SHARE_POST_SUCCESS = 'USER_SHARE_POST_SUCCESS';
export const USER_SHARE_POST_FAIL = 'USER_SHARE_POST_FAIL';

export const USER_ADD_VIEW_POST_REQUEST = 'USER_ADD_VIEW_POST_REQUEST';
export const USER_ADD_VIEW_POST_SUCCESS = 'USER_ADD_VIEW_POST_SUCCESS';
export const USER_ADD_VIEW_POST_FAIL = 'USER_ADD_VIEW_POST_FAIL';

export const USER_REPORT_ACC_REQUEST = 'USER_REPORT_ACC_REQUEST';
export const USER_REPORT_ACC_SUCCESS = 'USER_REPORT_ACC_SUCCESS';
export const USER_REPORT_ACC_FAIL = 'USER_REPORT_ACC_FAIL';
export const USER_REPORT_ACC_RESET = 'USER_REPORT_ACC_RESET';

export const USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST';
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS';
export const USER_SEARCH_FAIL = 'USER_SEARCH_FAIL';

export const USER_DELETE_ACCOUNT_REQUEST = 'USER_DELETE_ACCOUNT_REQUEST';
export const USER_DELETE_ACCOUNT_SUCCESS = 'USER_DELETE_ACCOUNT_SUCCESS';
export const USER_DELETE_ACCOUNT_FAIL = 'USER_DELETE_ACCOUNT_FAIL';

export const USER_ADD_RECENT_SEARCH_REQUEST = 'USER_ADD_RECENT_SEARCH_REQUEST';
export const USER_ADD_RECENT_SEARCH_SUCCESS = 'USER_ADD_RECENT_SEARCH_SUCCESS';
export const USER_ADD_RECENT_SEARCH_FAIL = 'USER_ADD_RECENT_SEARCH_FAIL';

export const USER_GET_RECENT_SEARCH_REQUEST = 'USER_GET_RECENT_SEARCH_REQUEST';
export const USER_GET_RECENT_SEARCH_SUCCESS = 'USER_GET_RECENT_SEARCH_SUCCESS';
export const USER_GET_RECENT_SEARCH_FAIL = 'USER_GET_RECENT_SEARCH_FAIL';

export const USER_CLEAR_RECENT_SEARCH_REQUEST =
    'USER_CLEAR_RECENT_SEARCH_REQUEST';
export const USER_CLEAR_RECENT_SEARCH_SUCCESS =
    'USER_CLEAR_RECENT_SEARCH_SUCCESS';
export const USER_CLEAR_RECENT_SEARCH_FAIL = 'USER_CLEAR_RECENT_SEARCH_FAIL';

export const USER_GET_NOTIFICATION_REQUEST = 'USER_GET_NOTIFICATION_REQUEST';
export const USER_GET_NOTIFICATION_SUCCESS = 'USER_GET_NOTIFICATION_SUCCESS';
export const USER_GET_NOTIFICATION_FAIL = 'USER_GET_NOTIFICATION_FAIL';

export const USER_SETTING_NOTIFICATION_REQUEST =
    'USER_SETTING_NOTIFICATION_REQUEST';
export const USER_SETTING_NOTIFICATION_SUCCESS =
    'USER_SETTING_NOTIFICATION_SUCCESS';
export const USER_SETTING_NOTIFICATION_FAIL = 'USER_SETTING_NOTIFICATION_FAIL';

export const USER_CHANGE_PASSWORD_REQUEST = 'USER_CHANGE_PASSWORD_REQUEST';
export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS';
export const USER_CHANGE_PASSWORD_FAIL = 'USER_CHANGE_PASSWORD_FAIL';

export const USER_LIST_NOTIFICATION_REQUEST = 'USER_LIST_NOTIFICATION_REQUEST';
export const USER_LIST_NOTIFICATION_SUCCESS = 'USER_LIST_NOTIFICATION_SUCCESS';
export const USER_LIST_NOTIFICATION_FAIL = 'USER_LIST_NOTIFICATION_FAIL';

export const USER_BLOCKED_YOU_REQUEST = 'USER_BLOCKED_YOU_REQUEST';
export const USER_BLOCKED_YOU_SUCCESS = 'USER_BLOCKED_YOU_SUCCESS';
export const USER_BLOCKED_YOU_FAIL = 'USER_BLOCKED_YOU_FAIL';

export const USER_SAVE_FCM_TOKEN_REQUEST = 'USER_SAVE_FCM_TOKEN_REQUEST';
export const USER_SAVE_FCM_TOKEN_SUCCESS = 'USER_SAVE_FCM_TOKEN_SUCCESS';
export const USER_SAVE_FCM_TOKEN_FAIL = 'USER_SAVE_FCM_TOKEN_FAIL';

export const USER_LANGUAGE_SUCCESS = 'USER_LANGUAGE_SUCCESS';
